// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/proto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Markdown service

type MarkdownService interface {
	RenderMarkdown(ctx context.Context, in *RenderMarkdownRequest, opts ...client.CallOption) (*RenderMarkdownResponse, error)
}

type markdownService struct {
	c    client.Client
	name string
}

func NewMarkdownService(name string, c client.Client) MarkdownService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "markdown"
	}
	return &markdownService{
		c:    c,
		name: name,
	}
}

func (c *markdownService) RenderMarkdown(ctx context.Context, in *RenderMarkdownRequest, opts ...client.CallOption) (*RenderMarkdownResponse, error) {
	req := c.c.NewRequest(c.name, "Markdown.RenderMarkdown", in)
	out := new(RenderMarkdownResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Markdown service

type MarkdownHandler interface {
	RenderMarkdown(context.Context, *RenderMarkdownRequest, *RenderMarkdownResponse) error
}

func RegisterMarkdownHandler(s server.Server, hdlr MarkdownHandler, opts ...server.HandlerOption) error {
	type markdown interface {
		RenderMarkdown(ctx context.Context, in *RenderMarkdownRequest, out *RenderMarkdownResponse) error
	}
	type Markdown struct {
		markdown
	}
	h := &markdownHandler{hdlr}
	return s.Handle(s.NewHandler(&Markdown{h}, opts...))
}

type markdownHandler struct {
	MarkdownHandler
}

func (h *markdownHandler) RenderMarkdown(ctx context.Context, in *RenderMarkdownRequest, out *RenderMarkdownResponse) error {
	return h.MarkdownHandler.RenderMarkdown(ctx, in, out)
}
