// Code generated by GCG. DO NOT EDIT.
// Go Code Generator 0.0.8 (https://github.com/OhYee/gcg)

package proto

import ()

// MessageType expression operator type
type MessageType uint8

// operator constant
const (
	_ MessageType = iota
	MessageTypeHeartBeat
	MessageTypeRequest
	MessageTypeResponse
)

var typeName = [...]string{
	"Unknown",
	"HeartBeat",
	"Request",
	"Response",
}

func (t MessageType) String() string {
	if int(t) > len(typeName) {
		return "Unknown"
	}
	return typeName[t]
}
