// Code generated by GCG. DO NOT EDIT.
// Go Code Generator 0.0.8 (https://github.com/OhYee/gcg)

package msg

import ()

// MessageType expression operator type
type MessageType uint8

// operator constant
const (
	_ MessageType = iota
	MessageTypeRequest
	MessageTypeResponse
	MessageTypeClose
)

// MessageTypeRequestHandle function to solve Request type message
type MessageTypeRequestHandle func(data *Request) (err error)

// MessageTypeResponseHandle function to solve Response type message
type MessageTypeResponseHandle func(data *Response) (err error)

// MessageTypeCloseHandle function to solve Close type message
type MessageTypeCloseHandle func(data *Close) (err error)

var typeName = [...]string{
	"Unknown",
	"Request",
	"Response",
	"Close",
}

func (t MessageType) String() string {
	if int(t) > len(typeName) {
		return "Unknown"
	}
	return typeName[t]
}
